services:
  rust:
    container_name: atcoder-rust
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

