condense_wildcard_suffixes = true
edition = "2018"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
chain_width = 100
