ci: (fmt "--check") check clippy nextest

[no-exit-message]
build *args:
    cargo build {{ args }}

[no-exit-message]
check *args:
    cargo check {{ args }}

alias r := run
[no-exit-message]
run *args:
    cargo run {{ args }}

[no-exit-message]
fmt *args:
    cargo fmt {{ args }}

[no-exit-message]
clippy *args:
    cargo clippy --package aclog {{ args }}

[no-exit-message]
nextest *args:
    cargo nextest run {{ args }}
