[no-exit-message]
run *args:
    cargo run -- {{ args }}

[no-exit-message]
build *args:
    cargo build -- {{ args }}

[no-exit-message]
check *args:
    cargo check -- {{ args }}

[no-exit-message]
clippy *args:
    cargo clippy -- {{ args }}

[no-exit-message]
fmt *args:
    cargo fmt -- {{ args }}

[no-exit-message]
nextest *args:
    cargo nextest run -- {{ args }}
